### PR TITLE
Add arm64 builds to pack.sh

### PR DESCRIPTION
**Pull request by nhooyr**
Updates https://github.com/cdr/code-server/issues/1505

### CODE REVIEW

**Comment by caleblloyd** [comment]
Thanks for the contribution, I'll publish v0.4 ARM build with this

**Comment by caleblloyd** [comment]
Actually it's been a while since this has been released, I'll go ahead and release v0.4.1 built on Golang 1.14.2

**Comment by caleblloyd** [comment]
https://github.com/boxboat/fixuid/releases/tag/v0.4.1

**Comment by nhooyr** [comment]
Thank you 🎊

**Pull request merged**
